### ISSUE TITLE
[bsicons_replacer] Icon names need to be trimmed?

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#11]
See [this edit](https://en.wikipedia.org/w/index.php?diff=next&oldid=796468218). `   CONTr` should have been changed to `   CONTgq`.

**Comment by JJMC89** [comment]
@jc86035 In `{{Routemap}}` are all icons permitted to be surrounded by whitespace?

**Comment by jc86035** [comment]
Yes, icon names are trimmed.

**Comment by JJMC89** [comment]
Whitespace needs to be accounted for in ROUTEMAP_BSICON.
