### ISSUE TITLE
[bsicons_replacer] Convert percent encodings and HTML character entities to Unicode characters

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#13]
Valid percent-encoding such as `%C3%9C` generates valid file names, as do HTML entities such as `&#xDC;` and `&#220;`. Except for space/zero-width characters like `&nbsp;` (as per MOS), these should be converted to Unicode if they form part of valid BSicon names (and replaced as usual if in the redirects list). (Alternately this could be done for just Ü and the Cyrillic Т.)

**Comment by JJMC89** [comment]
Can I get an example page for each case (percent, HTML) in a BSicon name for testing?

**Comment by JJMC89** [comment]
```python
>>> from html import unescape as html_unescape
>>> from urllib.parse import unquote as url_unquote
>>> html_unescape('T&#xDC;NNEL')
'TÜNNEL'
>>> html_unescape('T&#220;NNEL')
'TÜNNEL'
>>> url_unquote('T%C3%9CNNEL')
'TÜNNEL'
>>> html_unescape(url_unquote('T&#220;NNEL T%C3%9CNNEL'))
'TÜNNEL TÜNNEL'
>>> url_unquote(html_unescape('T&#220;NNEL T%C3%9CNNEL'))
'TÜNNEL TÜNNEL'
```

**Comment by jc86035** [comment]
You could use `ÜST` as a BSicon name and `ÜWc2` as a redirect name.
