### ISSUE TITLE
[bsicons_replacer] Bot should edit cswiki Template:Železniční trať

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#16]
BSicons should be replaced in the `předchozí typ`, `předchozí stan`, `následující stan` and `následující typ` parameters of [cs:Template:Železniční trať](https://cs.wikipedia.org/wiki/%C5%A0ablona:%C5%BDelezni%C4%8Dn%C3%AD_tra%C5%A5). There is also `typ`, which has `l` inserted after `ex` or at the start of the string. I don't think they wrote it very well (it should ideally insert `l` before the first match of `[bcdhoknpstvw3A-Z]`) but it's not really worth fixing.

**Comment by JJMC89** [comment]
It looks like [cs:Template:Železniční trať/napojení](https://cs.wikipedia.org/wiki/%C5%A0ablona:%C5%BDelezni%C4%8Dn%C3%AD_tra%C5%A5/napojen%C3%AD), which uses the same parameters, should also be included.

**Comment by jc86035** [comment]
(I thought that was a subtemplate and didn't include it.)
