### ISSUE TITLE
[bsicons_replacer] [Request] Find/replace for bsq/bso templates

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#17]
Replacement script should replace `{{BSicon quote|«oldname»}}` with `{{bsq|«newname»|alt=«oldname»}}` and replace normally any numbered parameters of `{{BS-o}}` if there is no `txt=` parameter.

**Comment by JJMC89** [comment]
This issue was moved to JJMC89/bsiconsbot#2
