### ISSUE TITLE
[bsicons_replacer] HTML comments in {{Routemap}} can prevent replacement

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#23]
[Main–Lahn Railway](https://en.wikipedia.org/wiki/Main-Lahn_Railway) has some icons which haven't been replaced, probably because they are at the end of their row with a hidden comment to the right and the regex doesn't recognize it.

**Comment by JJMC89** [comment]
`ROUTEMAP_BSICON` should match them, however HTML comments aren't stripped when determining the `current_icon`.

**Comment by JJMC89** [comment]
Resolved with 122a70a
