### ISSUE TITLE
Title preceding <includeonly> is not recognized

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#25]
[Template:Macclesfield, Bollington and Marple Railway RDT](https://en.wikipedia.org/wiki/Template:Macclesfield,_Bollington_and_Marple_Railway_RDT) is not being edited by the bot, probably because of `{{Routemap<includeonly>|inline=1</includeonly>` (I suspect the title is being read as `Routemap<includeonly>`). Not really a big deal and can be solved without changing the script by moving the opening includeonly tag to after the equals sign.

This also occurs on [this diagram](https://en.wikipedia.org/wiki/Template:Belfast%E2%80%93Larne_railway_line_routemap) and maybe a few others.

**Comment by JJMC89** [comment]
```<includeonly>``` does interfere with the template title. I don't think it is worth the investment to work around the issue; please just move them.
