### ISSUE TITLE
No redirects are being replaced

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#29]
There are several redirects in use at [w:en:Template:RTD expansion map](https://en.wikipedia.org/wiki/Template:RTD_expansion_map). They should have been replaced by May 23, but it appears that no redirects are currently being replaced. As I mentioned in a comment on #28, this may be due to the length of the redirect list, which could be split into two pages based on page ID (to avoid diagrams being edited multiple times after a page move) such that the lists are to be used for redirect replacement on different days.

Alternately, unused redirects (defined as "unused outside the User: namespace on all WMF wikis") could have their own list, and those could be sorted out of the replacement list. I have been using [this Quarry query](https://quarry.wmflabs.org/query/20170) manually and using BBEdit to successively filter the complete list of redirects, but it would be nice if your bot could generate the list by itself.

(It would also help to filter out redirects which should never be replaced from the wikitext lists, and maybe the list of exceptions could be kept in some other list. None of this is really necessary, since I only mass-nominate pages for deletion once every few months. However, the bot could itself tag pages with CSD G6, since it has been suggested that I do not need to go through the regular deletion process to uncontroversially delete redirects.)

**Comment by JJMC89** [comment]
The bot's grid job on Toolforge was stuck since 2018-05-22 13:57:18. I've manually restarted the job.

I don't know what caused it to get stuck. The last action in the log was that it was retrying an API query.

FYI: You can check the job status [here](https://tools.wmflabs.org/grid-jobs/tool/jjmc89-bot) (bsicons_replacer). Since it is run daily 'Total seen' should be 6 or 7.

**Comment by jc86035** [comment]
Sorry about that. I guess this can be closed now, since the stall was probably caused by the Wikibase-related server errors.

**Comment by JJMC89** [comment]
> Sorry about that. I guess this can be closed now, since the stall was probably caused by the Wikibase-related server errors.

No worries. I didn't know it was stuck until you filed this.
