### ISSUE TITLE
File names in galleries are not replaced

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#30]
Galleries omit "File:". This seems to stop BSicons from being replaced; "BSicon $1.svg" should be replaced. Almost all usage in galleries is in bot-generated user pages.

**Comment by JJMC89** [comment]
Gallery syntax isn't currently supported, but it shouldn't be difficult to implement.

**Comment by JJMC89** [comment]
This issue was moved to JJMC89/bsiconsbot#4
