### ISSUE TITLE
[Request] CSD-G6 unused BSicon redirects

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#31]
It would be nice if it were possible for redirects not used outside the User namespace on any WMF wikis and not contained in any of the exception categories to be automatically tagged for speedy deletion under criterion G6. Currently I manually filter the complete list every few months using BBEdit, a Quarry query and PetScan queries.

**Comment by JJMC89** [comment]
Please start a discussion about having a bot do this so that I can link it in the approval request. I expect that it would be uncontroversial.

**Comment by JJMC89** [comment]
This issue was moved to JJMC89/bsiconsbot#5
