### ISSUE TITLE
[request] Allow BSicon replacement without a config

### ISSUE THREAD

**Issue by jc86035** [JJMC89/JJMC89_bot#6]
Could the current English Wikipedia settings be used as default if there isn't a config found? It would let me focus more on translating the edit summary instead of copying and pasting the same list of templates.

**Comment by JJMC89** [comment]
This is doable. I'll likely implement a "global" config, but I think it would be better to host it on Commons.

**Comment by JJMC89** [comment]
@jc86035 You can create the global config at [commons:User:JJMC89 bot/config/BSiconsReplacer/global](https://commons.wikimedia.org/wiki/User:JJMC89_bot/config/BSiconsReplacer/global). Wikis using the same templates can then just have a `summary_prefix` in the local config.

**Comment by jc86035** [comment]
Thanks, that should work for most wikis.
